### ISSUE TITLE
UI brokenness

### ISSUE THREAD

**Issue by tycho** [Yubico/yubioath-desktop#161]
I don't know what caused this, but I installed 4.1.2 on a relatively fresh install of Windows 10 15063 (only had base drivers installed plus the authenticator) and got this:

![2017-05-12](https://cloud.githubusercontent.com/assets/29616/26022186/e57201d4-3752-11e7-8d17-61167f3108cc.png)
![2017-05-12 1](https://cloud.githubusercontent.com/assets/29616/26022187/e5760950-3752-11e7-9ec6-80119380f374.png)

Clearly shouldn't look like that.

**Comment by tycho** [comment]
Issue went away, still not sure what caused it.

**Comment by tycho** [comment]
Actually, reopening because I figured out what this is. Apparently the current version of the Yubico Authenticator requires an OpenGL context. I only noticed because I had screwy video drivers that were warping all the framebuffers in a weird way (as seen in the earlier screenshots).

My dad, on the other hand, discovered it because he has an old machine that is pre-OpenGL 2.0 and refuses to run the program:

![pre-OpenGL 2.0 unhappiness](http://i.imgur.com/cxwjrix.png)

It is ridiculous that this app should require an OpenGL context in order to render basic UI elements and text. What was wrong with the almost-entirely-Python version you guys had before? It worked wonderfully, aside from the timer quirks (broken when suspending/resuming and timer that keeps running while minimized to the tray).

**Comment by dagheyman** [comment]
> My dad, on the other hand, discovered it because he has an old machine that is pre-OpenGL 2.0 and refuses to run the program:

Can you double check that he is running the latest version? Because this error (or variant of it at least) was fixed in 4.1.1, see #159.

> It is ridiculous that this app should require an OpenGL context in order to render basic UI elements and text.

It can use DirectX with the ANGLE library as well, see this [link](https://wiki.qt.io/Qt_5_on_Windows_ANGLE_and_OpenGL).

> What was wrong with the almost-entirely-Python version you guys had before?

Some of the reasons we moved away from the old stack:
- It was based on PySide and Qt4, which is [not supported](http://blog.qt.io/blog/2014/11/27/qt-4-8-x-support-to-be-extended-for-another-year/) anymore.
 - We wanted to be able to use the deployment methods directly provided by Qt and not rely on third party tooling like PyInstaller.
- We liked the declarative style of QML.

**Comment by tycho** [comment]
He installed from `yubioath-desktop-4.1.2-win.exe` when he ran into that error.

I think you might have missed my point -- or maybe you were just pointing out an alternative that might  work, I can't be sure... Why does it require any kind of hardware-accelerated graphics context in order to run? Whether it's OpenGL or DirectX isn't really the point. It's not a graphically intensive app, it's drawing simple UI elements. I recognize that Qt+QML _supports_ more elaborate UIs, but that's not what we have here. It seems extremely heavyweight for what should be an extremely small and lightweight app.

Understood about the PySide/Qt4 deprecation. It's sad that it means we have to have an app that's larger, and has additional odd requirements in order to run.

**Comment by dagheyman** [comment]
> He installed from yubioath-desktop-4.1.2-win.exe when he ran into that error.

Ok. So to be able to try to reproduce it, could you provide some more information about his system? Windows 10 and no OpenGL 2?

> Why does it require any kind of hardware-accelerated graphics context in order to run? Whether it's OpenGL or DirectX isn't really the point. It's not a graphically intensive app, it's drawing simple UI elements. I recognize that Qt+QML supports more elaborate UIs, but that's not what we have here. It seems extremely heavyweight for what should be an extremely small and lightweight app.

I see your point, and I don't disagree with that it can feel a bit heavy. I'm not sure there are any good lightweight alternatives to Qt5 when looking for a supported cross-platform framework though. [Here](http://blog.qt.io/blog/2016/08/15/the-qt-quick-graphics-stack-in-qt-5-8/) is some more reading about the current graphics drivers situation on Windows in Qt5. Looks like they are aware of the issues and it exists some alternative approaches (software rendering) that might be worth exploring.

**Comment by tycho** [comment]
His system's a really old Intel Atom netbook (Atom N270, if I recall correctly). It should be running Windows 10 32-bit, and no OpenGL 2.0.

I built him a 32-bit version of the v3.1.x Yubico Authenticator with my timer and power efficiency fixes I wrote tonight, so he may be happy without the v4.x version anyway. But I can ask him.

**Comment by tycho** [comment]
@dagheyman Did you evaluate PyQt5 as an upgrade path? I did a port of Yubico Authenticator v3.x from PySide to PyQt5 this afternoon and it seems to work perfectly. https://github.com/tycho/yubioath-desktop/commit/53659fbcdfa7a63fa45b49a05890b78022167307

One nice thing about PyQt5 is that it's almost a perfect drop-in-replacement for PySide. Some classes moved around (a bunch of `QtGui` classes are in `QtWidgets`), and the value `QImage.scanLine()` returns has some different semantics (you have to tell it the scanline size by doing `line.setsize(image.bytesPerLine())`). But those were pretty easy to fix.

**Comment by dagheyman** [comment]
> Did you evaluate PyQt5 as an upgrade path? 

Well, as you point out it is still depending on PyInstaller and we wanted to use QML for the GUI. I see now that PyQt5 mention a QML plugin, so that might be worth looking into at some point. The evaluation was done mostly for the [YubiKey Manager GUI](https://developers.yubico.com/yubikey-manager-qt/), for this project it was driven mainly by a wish to use the same technologies across our GUI projects.

I'm glad that you got at PyQt5 fork of v3.x to work for you, but we are quite happy with the PyOtherSide solution, so don't expect this project to switch back to that approach any time soon.

**Comment by tycho** [comment]
Hope you don't mind if I continue maintaining a PyQt5 fork, then. I fixed all the bugs that were bothering me and it works great for both me and my dad, so I don't really have much need to use the official branch (until new hardware comes along, in which case I'll have to do some feature backports). Here's hoping that future YubiKeys have more storage space for OATH tokens, I keep running up against the limit and having to cherry-pick which sites are on the token!

**Comment by EmFl** [comment]
Hello,
I'm having the same issue but sadly mine didn't go away :p 
I tried removing the HKEY_CURRENT_USER\Software\Yubico\Yubico Authenticator from the registry to reinitialise window position but it didn't change anything.

Because I'm missing the menu I can't add a new website to my yubikey ...

**Comment by dagheyman** [comment]
@EmFl Coul you try if the problem is still there with the 4.1.3 version?

**Comment by EmFl** [comment]
Just tried it but no change on my side sorry.

**Comment by EmFl** [comment]
Just to give more context, I tried uninstalling the 4.1.3 I had installed on top of 4.1.2. Made sure that the folder in program files was removed, deleted the folder AppData\Local\Yubico and the registry key HKEY_CURRENT_USER\Software\Yubico\Yubico Authenticator.
Then reinstalled 4.1.3 and the problem persists.

**Comment by dagheyman** [comment]
@EmFl Could you try setting a environment variable to `QT_OPENGL=angle` and then restarting the application?

**Comment by EmFl** [comment]
@dagheyman Sorry I couldn't try this before today, UI shows up nicely with this settings ! Should I keep it like this or is that an indicator of an issue that needs fixing ?
Thanks!

**Comment by dagheyman** [comment]
@EmFl Great, thanks for confirming. The next version we release will include a fix (https://github.com/Yubico/yubioath-desktop/commit/7f43dedd72c33337ab3e9dbf3d1b266712bf462c) so that this setting  isn't needed, you may keep the setting until it's released.

**Comment by Nesos-ita** [comment]
Not fully solved, i still ahve that problem:
-downloaded today the latest version
-updated video drivers to the latest version (from intel website)
-downloaded and executed directx setup (from microsoft) so that it installed eventually missing pieces.
-tested the enviroment variable (bot by using cmd "set QT_OPENGL=angle" and opening the app from cmd. also tested setting the env var from windows menu (both user var and system var+reboot)

still doesnt open and show the error message. dll files mentioned in the error are present in the applcication directory (automatically installed).
computer is an "acer aspire one"
here dxdiag log:
------------------
System Information
------------------
Time of this report: 9/7/2017, 15:16:25
       Machine name: UTENTE-PC
   Operating System: Windows 7 Professional 32-bit (6.1, Build 7601) Service Pack 1 (7601.win7sp1_ldr.170707-0600)
           Language: Italian (Regional Setting: Italian)
System Manufacturer: Acer      
       System Model: Aspire one      
               BIOS: InsydeH2O Version V1.26
          Processor: Intel(R) Atom(TM) CPU N270   @ 1.60GHz (2 CPUs), ~1.6GHz
             Memory: 1024MB RAM
Available OS Memory: 1014MB RAM
          Page File: 601MB used, 1436MB available
        Windows Dir: C:\Windows
    DirectX Version: DirectX 11
DX Setup Parameters: Not found
   User DPI Setting: Using System DPI
 System DPI Setting: 96 DPI (100 percent)
    DWM DPI Scaling: Disabled
     DxDiag Version: 6.01.7601.17514 32bit Unicode

------------
DxDiag Notes
------------
      Display Tab 1: No problems found.
        Sound Tab 1: No problems found.
          Input Tab: No problems found.

--------------------
DirectX Debug Levels
--------------------
Direct3D:    0/4 (retail)
DirectDraw:  0/4 (retail)
DirectInput: 0/5 (retail)
DirectMusic: 0/5 (retail)
DirectPlay:  0/9 (retail)
DirectSound: 0/5 (retail)
DirectShow:  0/6 (retail)

---------------
Display Devices
---------------
          Card name: Mobile Intel(R) 945 Express Chipset Family
       Manufacturer: Intel Corporation
          Chip type: Intel(R) GMA 950
           DAC type: Internal
         Device Key: Enum\PCI\VEN_8086&DEV_27AE&SUBSYS_022F1025&REV_03
     Display Memory: 250 MB
   Dedicated Memory: 0 MB
      Shared Memory: 250 MB
       Current Mode: 1024 x 600 (32 bit) (60Hz)
       Monitor Name: Monitor generico Plug and Play
      Monitor Model: unknown
         Monitor Id: SEC554E
        Native Mode: 1024 x 600(p) (60.024Hz)
        Output Type: Internal
        Driver Name: igdumd32.dll
Driver File Version: 8.14.0010.1930 (English)
     Driver Version: 8.15.10.1930
        DDI Version: 9Ex
       Driver Model: WDDM 1.0
  Driver Attributes: Final Retail
   Driver Date/Size: 9/23/2009 20:18:08, 3829760 bytes
        WHQL Logo'd: Yes
    WHQL Date Stamp: 
  Device Identifier: {D7B78E66-64EE-11CF-1F74-2522A2C2C535}
          Vendor ID: 0x8086
          Device ID: 0x27AE
          SubSys ID: 0x022F1025
        Revision ID: 0x0003
 Driver Strong Name: oem5.inf:Intel.Mfg:i945GME0:8.15.10.1930:pci\ven_8086&dev_27ae
     Rank Of Driver: 00F42001
        Video Accel: ModeMPEG2_A ModeMPEG2_C 
   Deinterlace Caps: {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(YUY2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(YUY2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(UYVY,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(UYVY,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(YV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(YV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(NV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(NV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC1,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC1,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC3,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC3,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC4,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC4,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
       D3D9 Overlay: Not Supported
            DXVA-HD: Not Supported
       DDraw Status: Enabled
         D3D Status: Enabled
         AGP Status: Enabled

-------------
Sound Devices
-------------
            Description: Altoparlanti (Dispositivo High Definition Audio)
 Default Sound Playback: Yes
 Default Voice Playback: Yes
            Hardware ID: HDAUDIO\FUNC_01&VEN_10EC&DEV_0272&SUBSYS_1025022F&REV_1000
        Manufacturer ID: 1
             Product ID: 65535
                   Type: WDM
            Driver Name: HdAudio.sys
         Driver Version: 6.01.7601.17514 (Italian)
      Driver Attributes: Final Retail
            WHQL Logo'd: Yes
          Date and Size: 11/20/2010 23:29:03, 304128 bytes
            Other Files: 
        Driver Provider: Microsoft
         HW Accel Level: Basic
              Cap Flags: 0xF1F
    Min/Max Sample Rate: 100, 200000
Static/Strm HW Mix Bufs: 1, 0
 Static/Strm HW 3D Bufs: 0, 0
              HW Memory: 0
       Voice Management: No
 EAX(tm) 2.0 Listen/Src: No, No
   I3DL2(tm) Listen/Src: No, No
Sensaura(tm) ZoomFX(tm): No

---------------------
Sound Capture Devices
---------------------
            Description: Microfono (Dispositivo High Definition Audio)
  Default Sound Capture: Yes
  Default Voice Capture: Yes
            Driver Name: HdAudio.sys
         Driver Version: 6.01.7601.17514 (Italian)
      Driver Attributes: Final Retail
          Date and Size: 11/20/2010 23:29:03, 304128 bytes
              Cap Flags: 0x1
           Format Flags: 0xFFFFF

-------------------
DirectInput Devices
-------------------
      Device Name: Mouse
         Attached: 1
    Controller ID: n/a
Vendor/Product ID: n/a
        FF Driver: n/a

      Device Name: Tastiera
         Attached: 1
    Controller ID: n/a
Vendor/Product ID: n/a
        FF Driver: n/a

Poll w/ Interrupt: No

-----------
USB Devices
-----------
+ Hub radice USB
| Vendor/Product ID: 0x8086, 0x27CB
| Matching Device ID: usb\root_hub
| Service: usbhub
| Driver: usbhub.sys, 11/27/2013 03:14:25, 258560 bytes
| Driver: usbd.sys, 11/27/2013 03:13:33, 6016 bytes

----------------
Gameport Devices
----------------

------------
PS/2 Devices
------------
+ Tastiera PS/2 standard
| Matching Device ID: *pnp0303
| Service: i8042prt
| Driver: i8042prt.sys, 7/14/2009 01:11:24, 80896 bytes
| Driver: kbdclass.sys, 7/14/2009 03:20:36, 42576 bytes
| 
+ Driver tastiera di Terminal Server
| Matching Device ID: root\rdp_kbd
| Upper Filters: kbdclass
| Service: TermDD
| Driver: i8042prt.sys, 7/14/2009 01:11:24, 80896 bytes
| Driver: kbdclass.sys, 7/14/2009 03:20:36, 42576 bytes
| 
+ Mouse compatibile PS/2
| Matching Device ID: *pnp0f13
| Service: i8042prt
| Driver: i8042prt.sys, 7/14/2009 01:11:24, 80896 bytes
| Driver: mouclass.sys, 7/14/2009 03:20:44, 41552 bytes
| 
+ Driver mouse di Terminal Server
| Matching Device ID: root\rdp_mou
| Upper Filters: mouclass
| Service: TermDD
| Driver: termdd.sys, 11/20/2010 23:29:03, 53120 bytes
| Driver: sermouse.sys, 7/14/2009 01:45:08, 19968 bytes
| Driver: mouclass.sys, 7/14/2009 03:20:44, 41552 bytes

------------------------
Disk & DVD/CD-ROM Drives
------------------------
      Drive: C:
 Free Space: 126.7 GB
Total Space: 152.5 GB
File System: NTFS
      Model: ST9160314AS ATA Device

--------------
System Devices
--------------
     Name: Intel(R) 82801G (ICH7 Family) PCI Express Root Port - 27D0
Device ID: PCI\VEN_8086&DEV_27D0&SUBSYS_022F1025&REV_02\3&21436425&0&E0
   Driver: C:\Windows\system32\DRIVERS\pci.sys, 6.01.7601.17514 (Italian), 11/20/2010 23:29:03, 153984 bytes

     Name: Mobile Intel(R) 945 Express Chipset Family
Device ID: PCI\VEN_8086&DEV_27AE&SUBSYS_022F1025&REV_03\3&21436425&0&10
   Driver: n/a

     Name: Intel(R) 82801G (ICH7 Family) USB2 Enhanced Host Controller - 27CC
Device ID: PCI\VEN_8086&DEV_27CC&SUBSYS_022F1025&REV_02\3&21436425&0&EF
   Driver: C:\Windows\system32\drivers\usbehci.sys, 6.01.7601.18328 (English), 11/27/2013 03:13:41, 43520 bytes
   Driver: C:\Windows\system32\drivers\usbport.sys, 6.01.7601.18328 (Italian), 11/27/2013 03:13:46, 284672 bytes
   Driver: C:\Windows\system32\drivers\usbhub.sys, 6.01.7601.18328 (Italian), 11/27/2013 03:14:25, 258560 bytes

     Name: Mobile Intel(R) 945GME Express Processor to DRAM Controller - 27AC
Device ID: PCI\VEN_8086&DEV_27AC&SUBSYS_022F1025&REV_03\3&21436425&0&00
   Driver: n/a

     Name: Intel(R) 82801G (ICH7 Family) USB Universal Host Controller - 27CB
Device ID: PCI\VEN_8086&DEV_27CB&SUBSYS_022F1025&REV_02\3&21436425&0&EB
   Driver: C:\Windows\system32\drivers\usbuhci.sys, 6.01.7601.18328 (English), 11/27/2013 03:13:36, 24064 bytes
   Driver: C:\Windows\system32\drivers\usbport.sys, 6.01.7601.18328 (Italian), 11/27/2013 03:13:46, 284672 bytes
   Driver: C:\Windows\system32\drivers\usbhub.sys, 6.01.7601.18328 (Italian), 11/27/2013 03:14:25, 258560 bytes

     Name: Mobile Intel(R) 945 Express Chipset Family
Device ID: PCI\VEN_8086&DEV_27A6&SUBSYS_022F1025&REV_03\3&21436425&0&11
   Driver: n/a

     Name: Intel(R) 82801G (ICH7 Family) SMBus Controller - 27DA
Device ID: PCI\VEN_8086&DEV_27DA&SUBSYS_022F1025&REV_02\3&21436425&0&FB
   Driver: n/a

     Name: Intel(R) 82801G (ICH7 Family) USB Universal Host Controller - 27CA
Device ID: PCI\VEN_8086&DEV_27CA&SUBSYS_022F1025&REV_02\3&21436425&0&EA
   Driver: C:\Windows\system32\drivers\usbuhci.sys, 6.01.7601.18328 (English), 11/27/2013 03:13:36, 24064 bytes
   Driver: C:\Windows\system32\drivers\usbport.sys, 6.01.7601.18328 (Italian), 11/27/2013 03:13:46, 284672 bytes
   Driver: C:\Windows\system32\drivers\usbhub.sys, 6.01.7601.18328 (Italian), 11/27/2013 03:14:25, 258560 bytes

     Name: Bridge Intel(R) 82801 PCI - 2448
Device ID: PCI\VEN_8086&DEV_2448&SUBSYS_022F1025&REV_E2\3&21436425&0&F0
   Driver: C:\Windows\system32\DRIVERS\pci.sys, 6.01.7601.17514 (Italian), 11/20/2010 23:29:03, 153984 bytes

     Name: Controller per High Definition Audio
Device ID: PCI\VEN_8086&DEV_27D8&SUBSYS_022F1025&REV_02\3&21436425&0&D8
   Driver: C:\Windows\system32\DRIVERS\hdaudbus.sys, 6.01.7601.17514 (Italian), 11/20/2010 23:29:03, 108544 bytes

     Name: Intel(R) 82801G (ICH7 Family) USB Universal Host Controller - 27C9
Device ID: PCI\VEN_8086&DEV_27C9&SUBSYS_022F1025&REV_02\3&21436425&0&E9
   Driver: C:\Windows\system32\drivers\usbuhci.sys, 6.01.7601.18328 (English), 11/27/2013 03:13:36, 24064 bytes
   Driver: C:\Windows\system32\drivers\usbport.sys, 6.01.7601.18328 (Italian), 11/27/2013 03:13:46, 284672 bytes
   Driver: C:\Windows\system32\drivers\usbhub.sys, 6.01.7601.18328 (Italian), 11/27/2013 03:14:25, 258560 bytes

     Name: Atheros AR8132 PCI-E Fast Ethernet Controller (NDIS 6.20)
Device ID: PCI\VEN_1969&DEV_1062&SUBSYS_022F1025&REV_C0\4&2AE4FDBA&0&00E2
   Driver: C:\Windows\system32\DRIVERS\L1C62x86.sys, 1.00.0000.0004 (English), 7/14/2009 00:02:47, 50688 bytes

     Name: Intel(R) 82801G (ICH7 Family) PCI Express Root Port - 27D6
Device ID: PCI\VEN_8086&DEV_27D6&SUBSYS_022F1025&REV_02\3&21436425&0&E3
   Driver: C:\Windows\system32\DRIVERS\pci.sys, 6.01.7601.17514 (Italian), 11/20/2010 23:29:03, 153984 bytes

     Name: Intel(R) 82801G (ICH7 Family) USB Universal Host Controller - 27C8
Device ID: PCI\VEN_8086&DEV_27C8&SUBSYS_022F1025&REV_02\3&21436425&0&E8
   Driver: C:\Windows\system32\drivers\usbuhci.sys, 6.01.7601.18328 (English), 11/27/2013 03:13:36, 24064 bytes
   Driver: C:\Windows\system32\drivers\usbport.sys, 6.01.7601.18328 (Italian), 11/27/2013 03:13:46, 284672 bytes
   Driver: C:\Windows\system32\drivers\usbhub.sys, 6.01.7601.18328 (Italian), 11/27/2013 03:14:25, 258560 bytes

     Name: Intel(R) 82801G (ICH7 Family) PCI Express Root Port - 27D4
Device ID: PCI\VEN_8086&DEV_27D4&SUBSYS_022F1025&REV_02\3&21436425&0&E2
   Driver: C:\Windows\system32\DRIVERS\pci.sys, 6.01.7601.17514 (Italian), 11/20/2010 23:29:03, 153984 bytes

     Name: Controller ATA seriale standard AHCI 1.0
Device ID: PCI\VEN_8086&DEV_27C5&SUBSYS_022F1025&REV_02\3&21436425&0&FA
   Driver: C:\Windows\system32\DRIVERS\msahci.sys, 6.01.7601.17514 (English), 11/20/2010 23:29:03, 28032 bytes
   Driver: C:\Windows\system32\DRIVERS\pciidex.sys, 6.01.7600.16385 (Italian), 7/14/2009 03:19:03, 42560 bytes
   Driver: C:\Windows\system32\DRIVERS\atapi.sys, 6.01.7600.16385 (English), 7/14/2009 03:26:15, 21584 bytes
   Driver: C:\Windows\system32\DRIVERS\ataport.sys, 6.01.7601.18231 (Italian), 8/5/2013 03:56:47, 133056 bytes

     Name: Intel(R) 82801G (ICH7 Family) PCI Express Root Port - 27D2
Device ID: PCI\VEN_8086&DEV_27D2&SUBSYS_022F1025&REV_02\3&21436425&0&E1
   Driver: C:\Windows\system32\DRIVERS\pci.sys, 6.01.7601.17514 (Italian), 11/20/2010 23:29:03, 153984 bytes

     Name: Intel(R) 82801GBM (ICH7-M/U) LPC Interface Controller - 27B9
Device ID: PCI\VEN_8086&DEV_27B9&SUBSYS_022F1025&REV_02\3&21436425&0&F8
   Driver: C:\Windows\system32\DRIVERS\msisadrv.sys, 6.01.7600.16385 (English), 7/14/2009 03:20:43, 13888 bytes

------------------
DirectShow Filters
------------------

DirectShow Filters:
WMAudio Decoder DMO,0x00800800,1,1,WMADMOD.DLL,6.01.7601.19091
WMAPro over S/PDIF DMO,0x00600800,1,1,WMADMOD.DLL,6.01.7601.19091
WMSpeech Decoder DMO,0x00600800,1,1,WMSPDMOD.DLL,6.01.7601.19091
MP3 Decoder DMO,0x00600800,1,1,mp3dmod.dll,6.01.7601.19091
Mpeg4s Decoder DMO,0x00800001,1,1,mp4sdecd.dll,6.01.7601.19091
WMV Screen decoder DMO,0x00600800,1,1,wmvsdecd.dll,6.01.7601.19091
WMVideo Decoder DMO,0x00800001,1,1,wmvdecod.dll,6.01.7601.19091
Mpeg43 Decoder DMO,0x00800001,1,1,mp43decd.dll,6.01.7601.19091
Mpeg4 Decoder DMO,0x00800001,1,1,mpg4decd.dll,6.01.7601.19091
DV Muxer,0x00400000,0,0,qdv.dll,6.06.7601.17514
Color Space Converter,0x00400001,1,1,quartz.dll,6.06.7601.23709
WM ASF Reader,0x00400000,0,0,qasf.dll,12.00.7601.19091
Screen Capture filter,0x00200000,0,1,wmpsrcwp.dll,12.00.7601.17514
AVI Splitter,0x00600000,1,1,quartz.dll,6.06.7601.23709
VGA 16 Color Ditherer,0x00400000,1,1,quartz.dll,6.06.7601.23709
SBE2MediaTypeProfile,0x00200000,0,0,sbe.dll,6.06.7601.17528
Microsoft DTV-DVD Video Decoder,0x005fffff,2,4,msmpeg2vdec.dll,12.00.9200.17037
AC3 Parser Filter,0x00600000,1,1,mpg2splt.ax,6.06.7601.17528
StreamBufferSink,0x00200000,0,0,sbe.dll,6.06.7601.17528
Microsoft TV Captions Decoder,0x00200001,1,0,MSTVCapn.dll,6.01.7601.17715
MJPEG Decompressor,0x00600000,1,1,quartz.dll,6.06.7601.23709
CBVA DMO wrapper filter,0x00200000,1,1,cbva.dll,6.01.7601.17514
MPEG-I Stream Splitter,0x00600000,1,2,quartz.dll,6.06.7601.23709
SAMI (CC) Parser,0x00400000,1,1,quartz.dll,6.06.7601.23709
VBI Codec,0x00600000,1,4,VBICodec.ax,6.06.7601.17514
MPEG-2 Splitter,0x005fffff,1,0,mpg2splt.ax,6.06.7601.17528
Closed Captions Analysis Filter,0x00200000,2,5,cca.dll,6.06.7601.17514
SBE2FileScan,0x00200000,0,0,sbe.dll,6.06.7601.17528
Microsoft MPEG-2 Video Encoder,0x00200000,1,1,msmpeg2enc.dll,6.01.7601.19091
Internal Script Command Renderer,0x00800001,1,0,quartz.dll,6.06.7601.23709
MPEG Audio Decoder,0x03680001,1,1,quartz.dll,6.06.7601.23709
DV Splitter,0x00600000,1,2,qdv.dll,6.06.7601.17514
Video Mixing Renderer 9,0x00200000,1,0,quartz.dll,6.06.7601.23709
Microsoft MPEG-2 Encoder,0x00200000,2,1,msmpeg2enc.dll,6.01.7601.19091
ACM Wrapper,0x00600000,1,1,quartz.dll,6.06.7601.23709
Video Renderer,0x00800001,1,0,quartz.dll,6.06.7601.23709
MPEG-2 Video Stream Analyzer,0x00200000,0,0,sbe.dll,6.06.7601.17528
Line 21 Decoder,0x00600000,1,1,qdvd.dll,6.06.7601.23471
Video Port Manager,0x00600000,2,1,quartz.dll,6.06.7601.23709
Video Renderer,0x00400000,1,0,quartz.dll,6.06.7601.23709
VPS Decoder,0x00200000,0,0,WSTPager.ax,6.06.7601.17514
WM ASF Writer,0x00400000,0,0,qasf.dll,12.00.7601.19091
VBI Surface Allocator,0x00600000,1,1,vbisurf.ax,6.01.7601.17514
File writer,0x00200000,1,0,qcap.dll,6.06.7601.17514
iTV Data Sink,0x00600000,1,0,itvdata.dll,6.06.7601.17514
iTV Data Capture filter,0x00600000,1,1,itvdata.dll,6.06.7601.17514
DVD Navigator,0x00200000,0,3,qdvd.dll,6.06.7601.23471
Microsoft TV Subtitles Decoder,0x00200001,1,0,MSTVCapn.dll,6.01.7601.17715
Overlay Mixer2,0x00200000,1,1,qdvd.dll,6.06.7601.23471
AVI Draw,0x00600064,9,1,quartz.dll,6.06.7601.23709
RDP DShow Redirection Filter,0xffffffff,1,0,DShowRdpFilter.dll,
Microsoft MPEG-2 Audio Encoder,0x00200000,1,1,msmpeg2enc.dll,6.01.7601.19091
WST Pager,0x00200000,1,1,WSTPager.ax,6.06.7601.17514
MPEG-2 Demultiplexer,0x00600000,1,1,mpg2splt.ax,6.06.7601.17528
DV Video Decoder,0x00800000,1,1,qdv.dll,6.06.7601.17514
SampleGrabber,0x00200000,1,1,qedit.dll,6.06.7601.19091
Null Renderer,0x00200000,1,0,qedit.dll,6.06.7601.19091
MPEG-2 Sections and Tables,0x005fffff,1,0,Mpeg2Data.ax,6.06.7601.17514
Microsoft AC3 Encoder,0x00200000,1,1,msac3enc.dll,6.01.7601.17514
StreamBufferSource,0x00200000,0,0,sbe.dll,6.06.7601.17528
Smart Tee,0x00200000,1,2,qcap.dll,6.06.7601.17514
Overlay Mixer,0x00200000,0,0,qdvd.dll,6.06.7601.23471
AVI Decompressor,0x00600000,1,1,quartz.dll,6.06.7601.23709
NetBridge,0x00200000,2,0,netbridge.dll,6.01.7601.17514
AVI/WAV File Source,0x00400000,0,2,quartz.dll,6.06.7601.23709
Wave Parser,0x00400000,1,1,quartz.dll,6.06.7601.23709
MIDI Parser,0x00400000,1,1,quartz.dll,6.06.7601.23709
Multi-file Parser,0x00400000,1,1,quartz.dll,6.06.7601.23709
File stream renderer,0x00400000,1,1,quartz.dll,6.06.7601.23709
Microsoft DTV-DVD Audio Decoder,0x005fffff,1,1,msmpeg2adec.dll,6.01.7601.23285
StreamBufferSink2,0x00200000,0,0,sbe.dll,6.06.7601.17528
AVI Mux,0x00200000,1,0,qcap.dll,6.06.7601.17514
Line 21 Decoder 2,0x00600002,1,1,quartz.dll,6.06.7601.23709
File Source (Async.),0x00400000,0,1,quartz.dll,6.06.7601.23709
File Source (URL),0x00400000,0,1,quartz.dll,6.06.7601.23709
Media Center Extender Encryption Filter,0x00200000,2,2,Mcx2Filter.dll,6.01.7601.17514
AudioRecorder WAV Dest,0x00200000,0,0,WavDest.dll,
AudioRecorder Wave Form,0x00200000,0,0,WavDest.dll,
SoundRecorder Null Renderer,0x00200000,0,0,WavDest.dll,
Infinite Pin Tee Filter,0x00200000,1,1,qcap.dll,6.06.7601.17514
Enhanced Video Renderer,0x00200000,1,0,evr.dll,6.01.7601.23471
BDA MPEG2 Transport Information Filter,0x00200000,2,0,psisrndr.ax,6.06.7601.17669
MPEG Video Decoder,0x40000001,1,1,quartz.dll,6.06.7601.23709

WDM Streaming Tee/Splitter Devices:
Convertitore a T/Sito a sito,0x00200000,1,1,ksproxy.ax,6.01.7601.19091

Video Compressors:
WMVideo8 Encoder DMO,0x00600800,1,1,wmvxencd.dll,6.01.7601.19091
WMVideo9 Encoder DMO,0x00600800,1,1,wmvencod.dll,6.01.7601.19091
MSScreen 9 encoder DMO,0x00600800,1,1,wmvsencd.dll,6.01.7601.19091
DV Video Encoder,0x00200000,0,0,qdv.dll,6.06.7601.17514
MJPEG Compressor,0x00200000,0,0,quartz.dll,6.06.7601.23709
Codec Cinepak di Radius,0x00200000,1,1,qcap.dll,6.06.7601.17514
Codec Intel IYUV,0x00200000,1,1,qcap.dll,6.06.7601.17514
Codec Intel IYUV,0x00200000,1,1,qcap.dll,6.06.7601.17514
Microsoft RLE,0x00200000,1,1,qcap.dll,6.06.7601.17514
Microsoft Video 1,0x00200000,1,1,qcap.dll,6.06.7601.17514

Audio Compressors:
WM Speech Encoder DMO,0x00600800,1,1,WMSPDMOE.DLL,6.01.7601.19091
WMAudio Encoder DMO,0x00600800,1,1,WMADMOE.DLL,6.01.7601.19091
IMA ADPCM,0x00200000,1,1,quartz.dll,6.06.7601.23709
PCM,0x00200000,1,1,quartz.dll,6.06.7601.23709
Microsoft ADPCM,0x00200000,1,1,quartz.dll,6.06.7601.23709
GSM 6.10,0x00200000,1,1,quartz.dll,6.06.7601.23709
CCITT A-Law,0x00200000,1,1,quartz.dll,6.06.7601.23709
CCITT u-Law,0x00200000,1,1,quartz.dll,6.06.7601.23709
MPEG Layer-3,0x00200000,1,1,quartz.dll,6.06.7601.23709

Audio Capture Sources:
Microfono (Dispositivo High Def,0x00200000,0,0,qcap.dll,6.06.7601.17514

PBDA CP Filters:
PBDA DTFilter,0x00600000,1,1,CPFilters.dll,6.06.7601.19135
PBDA ETFilter,0x00200000,0,0,CPFilters.dll,6.06.7601.19135
PBDA PTFilter,0x00200000,0,0,CPFilters.dll,6.06.7601.19135

Midi Renderers:
Default MidiOut Device,0x00800000,1,0,quartz.dll,6.06.7601.23709
Microsoft GS Wavetable Synth,0x00200000,1,0,quartz.dll,6.06.7601.23709

WDM Streaming Capture Devices:
Microfono HD Audio 2,0x00200000,1,1,ksproxy.ax,6.01.7601.19091
WebCam,0x00200000,1,1,ksproxy.ax,6.01.7601.19091

WDM Streaming Rendering Devices:
Cuffia/altoparlanti HD Audio,0x00200000,1,1,ksproxy.ax,6.01.7601.19091

BDA Network Providers:
Microsoft ATSC Network Provider,0x00200000,0,1,MSDvbNP.ax,6.06.7601.17514
Microsoft DVBC Network Provider,0x00200000,0,1,MSDvbNP.ax,6.06.7601.17514
Microsoft DVBS Network Provider,0x00200000,0,1,MSDvbNP.ax,6.06.7601.17514
Microsoft DVBT Network Provider,0x00200000,0,1,MSDvbNP.ax,6.06.7601.17514
Microsoft Network Provider,0x00200000,0,1,MSNP.ax,6.06.7601.17514

Video Capture Sources:
WebCam,0x00200000,1,1,ksproxy.ax,6.01.7601.19091

Multi-Instance Capable VBI Codecs:
VBI Codec,0x00600000,1,4,VBICodec.ax,6.06.7601.17514

BDA Transport Information Renderers:
BDA MPEG2 Transport Information Filter,0x00600000,2,0,psisrndr.ax,6.06.7601.17669
MPEG-2 Sections and Tables,0x00600000,1,0,Mpeg2Data.ax,6.06.7601.17514

BDA CP/CA Filters:
Decrypt/Tag,0x00600000,1,1,EncDec.dll,6.06.7601.19135
Encrypt/Tag,0x00200000,0,0,EncDec.dll,6.06.7601.19135
PTFilter,0x00200000,0,0,EncDec.dll,6.06.7601.19135
XDS Codec,0x00200000,0,0,EncDec.dll,6.06.7601.19135

WDM Streaming Communication Transforms:
Convertitore a T/Sito a sito,0x00200000,1,1,ksproxy.ax,6.01.7601.19091

Audio Renderers:
Altoparlanti (Dispositivo High ,0x00200000,1,0,quartz.dll,6.06.7601.23709
Default DirectSound Device,0x00800000,1,0,quartz.dll,6.06.7601.23709
Default WaveOut Device,0x00200000,1,0,quartz.dll,6.06.7601.23709
DirectSound: Altoparlanti (Dispositivo High Definition Audio),0x00200000,1,0,quartz.dll,6.06.7601.23709

---------------
EVR Power Information
---------------
Current Setting: {5C67A112-A4C9-483F-B4A7-1D473BECAFDC} (Quality) 
  Quality Flags: 2576
    Enabled:
    Force throttling
    Allow half deinterlace
    Allow scaling
    Decode Power Usage: 100
  Balanced Flags: 1424
    Enabled:
    Force throttling
    Allow batching
    Force half deinterlace
    Force scaling
    Decode Power Usage: 50
  PowerFlags: 1424
    Enabled:
    Force throttling
    Allow batching
    Force half deinterlace
    Force scaling
    Decode Power Usage: 0
