### ISSUE TITLE
Yubico Authenticator hangs, states (Not Responding) Windows 10

### ISSUE THREAD

**Issue by webwizardguy** [Yubico/yubioath-desktop#678]
- Yubico Authenticator version: 5.0.4 Win 64
- Operating system and version: Windows 10 19042.685
- YubiKey model and version: YubiKey 5 NFC
- Bug description summary: When I attempt to open the program it hangs, the window is all white, and it states (Not Responding)

Steps to reproduce
---

Nothing, just stopped working, it did this before, and rebooting eventually made it came back, but now it's not responding after numerous troubleshooting, uninstall, reinstall, Windows App version, Windows EXE version, nothing.

Expected result
---

I expect to see the window show all my Yubikey credentials on it.

Actual results
---

A blank screen.

Other info
---

Yubikey Manager does the same thing too, even though it was working the first few times.

**Comment by nevun** [comment]
This sounds exactly like https://github.com/Yubico/yubioath-desktop/issues/673
Open a cmd shell and do:
```
set QT_OPENGL=software
yubioath-desktop.exe
```

**Comment by webwizardguy** [comment]
Hello @nevun, that worked!

I had read that other issue and tried this solution before, but I was not running that command in the proper directory.  After running it in the proper directory it now works!

C:\Program Files\Yubico\Yubico Authenticator>set QT_OPENGL=software
C:\Program Files\Yubico\Yubico Authenticator>yubioath-desktop.exe

I tried the same thing for Yubikey Manager and it works now too...

C:\Program Files\Yubico\YubiKey Manager>set QT_OPENGL=software
C:\Program Files\Yubico\YubiKey Manager>ykman-gui.exe

Thank you!

**Comment by webwizardguy** [comment]
Hello @nevun , it does seem that in order to run the program I have to run those commands each time. They don't seem to stick. So if a close the program or reboot my machine I have to run those commands to get it going again.

**Comment by nevun** [comment]
I am no expert on Windows but it seems QT and your GPU drivers are not cooperating. If I were you I would try to play around a bit with upgrading graphic card drivers, tweaking all settings related to it.

Maybe Yubico could also consider turning off graphic accelerations by default in QT if possible, not my call though.

**Comment by luncinia** [comment]
Hello @nevun and @webwizardguy,  if your environment variables to have QT_OPENGL = software this should fix the issue and have it stick.  You can set it by using a command prompt in administrator mode and typing
`SETX QT_OPENGL software`

Or you can go through the control panel under system properties, advanced, environment variables to add this setting

**Comment by webwizardguy** [comment]
Thank you soooo much @luncinia, that fixed the problem for me, finally!!

**Comment by mooleshacat** [comment]
Testing now. Problem is it crashed after long period of being opened. Will check this ticket tomorrow and edit comment for update.

**Comment by macflyhub** [comment]
2022 and this issue still persists on many computers.. 
Only fix is still..
C:\Program Files\Yubico\YubiKey Manager>set QT_OPENGL=software
C:\Program Files\Yubico\YubiKey Manager>ykman-gui.exe
